### ISSUE TITLE
Improve module/package structure

### ISSUE THREAD

**Issue by Impelon** [Impelon/PyGVisuals#2]
Currently this module/package is not set up optimally to be user-friendly...
(e.g. examples cannot be executed from inside the module/package -> external start-script
instead examples should be seperate from the rest of the module; see PyGame/examples - https://github.com/pygame/pygame/tree/master/examples)

The problem is, I do not know how to optimally set this up.

**Comment by hasii2011** [comment]
So could help with this as I tried to use it in my project.  I did a restructuring that did not require src to be part of the python package.  This required changing how all the __init__ package files were structured.   Additionally, required a slight change to the imports in the various widgets.  So this would be part 1 of getting it easily deployed.  How do you suggest getting these suggested updates to you?  On a branch?

**Comment by Impelon** [comment]
I'm currently out of town and I'll get back to you in more detail, when I'm
back ^^
I guess you could fork the project and change the experimental branch; or
as you proposed, a new branch. I guess both are good...
I'm sorry I can't look at your work rigth now and that you're getting just
this brief answer.

**Comment by hasii2011** [comment]
Completely understand no problem.

**Comment by Impelon** [comment]
So I'm back, and I'm very curious to see your solution to the problem... As I've mentioned, a separate branch is fine; I'll merge it, if I'm happy with it.

**Comment by hasii2011** [comment]
Yeah. So I made the decision to not just restructure it but to make it Python 3.x only (to get it to run tests).  So . . . . . . 

BTW, I don't think I have branch permission on this project

**Comment by Impelon** [comment]
Well, you don't need the permission; you can just fork it, make the changes there and make a pull request!

**Comment by hasii2011** [comment]
Ok, I'll do that

**Comment by ghost** [comment]
Did this ever happen?

**Comment by Impelon** [comment]
Well I did port PyGVisuals to Python3 (as you can see it's the new default-branch), I never did hear back from @hasii2011, though.

**Comment by ghost** [comment]
I'd like to use your work in a project. I'd hate to do this work if it has already been done by @hasii2011 though. I'll wait a day or two to see if he responds. It's not a lot of work to update the package structure.

For what it's worth, I would move the examples into a separate repository. The way you have it now, the examples would end up getting packaged into the distribution file (egg, whl, etc...) and shipped into production with whatever project takes a dependency on your package. It's possible to configure setup.py to exclude the examples, but I'd still prefer to keep the source tree of this repo focused on tests and production code.

**Comment by Impelon** [comment]
Well I'd do the work myself if I knew what I need to change, but as I've said I barely have any experience with packages (I mean I'm glad I got PyGVisuals working this far)... 

As for the examples; I was "inspired" by pygame deploying examples with their package, too. But I guess I could open up a seperate branch/repository for them.

**Comment by ghost** [comment]
It's well passed my bedtime here (01:00 hours). Tomorrow I'll take some
time to look at the package structure and make some suggestions. I did a
quick search and it seems pretty easy to exclude the examples from the
output by modifying setup.py. I agree with your argument about shipping
examples with the code, the pygame examples *are* particularly useful, so
we can try the exclude route first and see if that works. Thanks for
responding to my comments! It's very encouraging to see a responsive
package owner! :)

**Comment by Impelon** [comment]
Sounds good ^^

**Comment by ghost** [comment]
Apologies;  My original goal was to restructure.  Then I realized I only had a Python 3 environment and understood you wanted both Python 2 and 3 comparability.  The net-net is that I did not accomplish this work;  However, I will test the pip installable package in a virtual environment which was my first "want"

**Comment by ghost** [comment]
> Apologies; My original goal was to restructure. Then I realized I only had a Python 3 environment and understood you wanted both Python 2 and 3 comparability. The net-net is that I did not accomplish this work; However, I will test the pip installable package in a virtual environment which was my first "want"

I didn't install from PyPi, I put a github reference in my requirements file and fed it into pip with pip install -r requirements.txt.

**Comment by ghost** [comment]
Will you please show me your requirements.txt file?  Also, do we have an interest in publishing onto PyPi?

**Comment by ghost** [comment]
The second line is not an error. It sure does look like one though :D 

@hasii2013 
`
pygame

-e git+https://github.com/Impelon/PyGVisuals#egg=PyGVisuals
`

**Comment by Impelon** [comment]
> Also, do we have an interest in publishing onto PyPi?

So... I don't know how PyPi works, but I'd guess that it can't just grab changes from GitHub and I'm personally not interested in maintaining another platform. You are however free to do so, since PyGVisuals has a BSD Licence you can share it on other platforms to your liking.
