### ISSUE TITLE
Make PyGVisuals easily deployable

### ISSUE THREAD

**Issue by Impelon** [Impelon/PyGVisuals#3]
Currently PyGVisuals needs to be manually inserted into the pygame/lib/site-packages directory to be used globaly or manually added to PATH. 

I do not know the optimal/pythonic way to solve this.

**Comment by ghost** [comment]
I was able to install with pip so I'm thinking this is done?

**Comment by Impelon** [comment]
Ok, well, that's great ^^ 
I never tested it out so I didn't know (also I don't install python-packages very often, so like I've stated before, I have no idea how to actually do this, so I'm glad @kjkriegel solved this ^^)

**Comment by ghost** [comment]
I tried to install via pip and got this message:

>pip3 install PyGVisuals
Collecting PyGVisuals
  Could not find a version that satisfies the requirement PyGVisuals (from versions: )
No matching distribution found for PyGVisuals

--------------------
I don't think this was published to PyPi

**Comment by Impelon** [comment]
Might be something to invest time into someday

**Comment by Impelon** [comment]
Actually, let's move this to a new issue. See #16
