### ISSUE TITLE
Slight update to entry widget based on Python 3.6.x

### ISSUE THREAD

**Issue by hasii2011** [Impelon/PyGVisuals#9]
The line on or around 113 in entry.py

`char = event.unicode.encode("ascii", "ignore")`

should be

`char: str = event.unicode`

otherwise the input validation method "isNumber", used by the test programs fails with

File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyCharmEdu/src/pygvisuals/widgets/entry.py", line 117, in update
    and self._validation(self._text + char, self._text, self)):
TypeError: must be str, not bytes

**Comment by Impelon** [comment]
I noticed that the calling of self._validate is flawed eitherways, now that you mention that.

However, let's address the issue you mention: I'm trying to keep PyGVisuals running on python 2.7 and python 3 at the same time and I think I've been mostly successful with that. Personally I'm using 2.7; I know that's frowned upon. 
Will get around to make the necessary changes to entry.py.

**Comment by Impelon** [comment]
So I noticed, that there is no simple way to make it compatible for both versions.
Therefore the reasonable solution is to publish a version of PyGVisuals for Pyhton 3. Running 2to3 on PyGVisuals seems to produce good results. I'll close this issue, since I cannot solve it this way.
